=== Asierzubia/SAR_FINAL/SAR_FINAL/xml_dtd/guardarRespuestas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name='respuestas'>
        <xs:complexType><!--Es para indicar un tipo complejo, la etiqueta respuesta esta compuesta por otras etiquetas-->
            <xs:sequence> <!--Es una secuencia de respuestas, dentro de respuestas hay muchas respuestas-->
                <xs:element name='respuesta'><!--Tengo que aclarar si cada elemento es tipo complejo o no, si no lo es solo habrá un elemento por sequencia-->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name='nombre' type="xs:string"/>
                            <xs:element name='comentario' type="xs:string"/>
                            <xs:element name='fecha' type="xs:date"/><!--Valores validos son (yyyy-mm-dd) entro muchos otros-->
                        </xs:sequence>
                        <xs:attribute name='id_respuesta' type='xs:int'/><!--Pongo tipo int por que las id van a ser números, hasta 32 bits-->
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Asierzubia/SAR_FINAL/xml_dtd/guardarRespuestas.xml
<?xml version="1.0"?>
<respuestas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="guardarRespuestas.xsd">
<respuesta id_respuesta="1">
<nombre>Asier</nombre><comentario>Hola esta es la respuesta</comentario><fecha>20-05-15</fecha>
</respuesta>
<respuesta id_respuesta="1">
<nombre>Asier</nombre><comentario>diosiiiittttoooooo</comentario><fecha>20-05-15</fecha>
</respuesta>
<respuesta id_respuesta="1">
<nombre>Asier</nombre><comentario>dfgdfgfgdfg</comentario><fecha>20-05-15</fecha>
</respuesta>
<respuesta id_respuesta="1">
<nombre>Asier</nombre><comentario>dfg</comentario><fecha>20-05-15</fecha>
</respuesta>
<respuesta id_respuesta="4">
<nombre>Asier</nombre><comentario>Hola esta es la respuesta</comentario><fecha>20-05-15</fecha>
</respuesta>
<respuesta id_respuesta=""><nombre>listajajaja</nombre><comentario>camion</comentario><fecha>20-01-07</fecha><email mostrar="no">99@gmail.com</email></respuesta><respuesta id_respuesta="1"><nombre>camiones</nombre><comentario>surfean el rio</comentario><fecha>20-01-07</fecha><email mostrar="no">99@gmail.com</email></respuesta><respuesta id_respuesta="12"><nombre>asier_best</nombre><comentario>Esta es la primera respuesta</comentario><fecha>20-01-08</fecha><email mostrar="no">jeje@gmail.com</email></respuesta><respuesta id_respuesta="1"><nombre>asier</nombre><comentario>3e32e</comentario><fecha>20-01-09</fecha><email mostrar="no">99@gmail.com</email></respuesta></respuestas>

=== Asierzubia/SAR_FINAL/SAR_FINAL/xml_dtd/guardarRespuestas.xml
<?xml version="1.0"?>
<respuestas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="guardarRespuestas.xsd">
<respuesta id_respuesta="1"><nombre>Asier</nombre><comentario>guay</comentario><fecha>20-01-12</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="1"><nombre>asier</nombre><comentario>Sin duda</comentario><fecha>20-01-15</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="2"><nombre>as</nombre><comentario>Tienes razon</comentario><fecha>20-01-15</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="2"><nombre>asier</nombre><comentario>Claro</comentario><fecha>20-01-15</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="1"><nombre>Asier</nombre><comentario>ma&#xF1;ana toca rally</comentario><fecha>20-01-15</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="3"><nombre>Asier</nombre><comentario>No lo creo</comentario><fecha>20-01-15</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="4"><nombre>Asier</nombre><comentario>No sabes de coches compi</comentario><fecha>20-01-15</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="9"><nombre>Asier</nombre><comentario>Mejor subaru</comentario><fecha>20-01-17</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="8"><nombre>Asier</nombre><comentario>jajajajajaja</comentario><fecha>20-01-17</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="7"><nombre>Asier</nombre><comentario>Mejor coche japo</comentario><fecha>20-01-17</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="3"><nombre>Asier</nombre><comentario>Si lo es</comentario><fecha>20-01-17</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="5"><nombre>Asier</nombre><comentario>Inconfundible</comentario><fecha>20-01-17</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="6"><nombre>Asier</nombre><comentario>jajajaja no te lo crees ni tu</comentario><fecha>20-01-17</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="8"><nombre>Asier</nombre><comentario>increible</comentario><fecha>20-01-17</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="9"><nombre>Asier</nombre><comentario>que va</comentario><fecha>20-01-17</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="3"><nombre>Asier</nombre><comentario>motor 2JZ no digo m&#xE1;s</comentario><fecha>20-01-17</fecha><email>99@gmail.com</email></respuesta><respuesta id_respuesta="1"><nombre>Asier</nombre><comentario>toca Hondarribia</comentario><fecha>20-01-17</fecha><email>99@gmail.com</email></respuesta></respuestas>
